-- MySQL Script generated by MySQL Workbench
-- dim. 09 avril 2017 15:51:54 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema node_api
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema node_api
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `node_api` DEFAULT CHARACTER SET latin1 ;
USE `node_api` ;

-- -----------------------------------------------------
-- Table `node_api`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `node_api`.`user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(45) NULL DEFAULT NULL,
  `lastname` VARCHAR(45) NULL DEFAULT NULL,
  `sex` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


-- -----------------------------------------------------
-- Data
-- -----------------------------------------------------
INSERT INTO user ('firstname','lastname','sex') values ('Adil','EL-YAMOUNI','Mal');
INSERT INTO user ('firstname','lastname','sex') values ('Hajar','EL-YAMOUNI','Femal');
INSERT INTO user ('firstname','lastname','sex') values ('Sami','EL-YAMOUNI','Mal');
INSERT INTO user ('firstname','lastname','sex') values ('Rama','EL-YAMOUNI','Femal');
